# frozen_string_literal: true


source 'https://rubygems.org'

gem 'gruff'

gem 'rmagick', '4.2.3'

gem 'faraday'

gem 'caracal'

gem 'rubocop'

gem 'google_drive'

gem 'google-apis-drive_v3'

gem 'google-api-client'